apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder
  namespace: stts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwarder
  template:
    metadata:
      labels:
        app: forwarder
    spec:
      containers:
        - name: forwarder
          image: stts/forwarder:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: stts-config
---
apiVersion: v1
kind: Service
metadata:
  name: forwarder
  namespace: stts
spec:
  selector:
    app: forwarder
  ports:
    - port: 50050
      targetPort: 50050
